export const ROLES = {
  SUPERADMIN: 'superadmin',
  ADMIN: 'admin',
  COORDINADOR: 'coordinador',
  PERSONERO: 'personero',
  PERSONERO_REGISTRADO: 'personero_registrado'
};

export const ELECTORAL_ROLES = [
  'Personero de Mesa',
  'Personero de Local de Votación',
  'Coordinador Zonal',
  'Coordinador Distrital'
];

export const TRAINING_RULES = {
  REQUIRED_VIDEOS: 1,
  REQUIRED_PDFS: 1,
  PASSING_QUIZ_STATUS: 'Aprobado',
  CREDENTIAL_CONFIRMED: 'Confirmado',
  CREDENTIAL_BLOCKED: 'Bloqueado'
};

export const DISTRITOS_LIMA = [
  "Ancón",
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Cercado de Lima",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "Comas",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Victoria",
  "Lince",
  "Los Olivos",
  "Lurigancho-Chosica",
  "Lurín",
  "Magdalena del Mar",
  "Miraflores",
  "Pachacámac",
  "Pucusana",
  "Pueblo Libre",
  "Puente Piedra",
  "Punta Hermosa",
  "Punta Negra",
  "Rímac",
  "San Bartolo",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santa María del Mar",
  "Santa Rosa",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa María del Triunfo",
  "Bellavista",
  "Callao",
  "Carmen de la Legua - Reynoso",
  "La Perla",
  "La Punta",
  "Mi Perú",
  "Ventanilla"
];

export const TOTAL_MESAS_LIMA = 32008;
export const TOTAL_MESAS_LIMA_METROPOLITANA = 26338;
export const TOTAL_MESAS_CALLAO = 2900;

export const PROVINCIA_METAS = {
  "LIMA": 26338,
  "CAÑETE": 673,
  "CANTA": 48,
  "HUARAL": 555,
  "HUAROCHIRI": 344,
  "CAJATAMBO": 24,
  "HUAURA": 655,
  "BARRANCA": 421,
  "OYON": 50,
  "CALLAO": 2900
};

export const DISTRITO_METAS = {
  "BREÑA": 349,
  "SAN VICENTE DE CAÑETE": 152,
  "CALANGO": 7,
  "CERRO AZUL": 23,
  "COAYLLO": 5,
  "CHILCA": 57,
  "IMPERIAL": 108,
  "LUNAHUANA": 13,
  "MALA": 86,
  "NUEVO IMPERIAL": 67,
  "PACARAN": 6,
  "QUILMANA": 47,
  "SAN ANTONIO": 151,
  "SAN LUIS": 228,
  "SANTA CRUZ DE FLORES": 9,
  "ZUÑIGA": 5,
  "ASIA": 38,
  "CARABAYLLO": 850,
  "CHORRILLOS": 899,
  "BARRANCO": 149,
  "CANTA": 10,
  "ARAHUAY": 3,
  "HUAMANTANGA": 3,
  "HUAROS": 4,
  "LACHAQUI": 4,
  "SAN BUENAVENTURA": 2,
  "SANTA ROSA DE QUIVES": 22,
  "HUARAL": 296,
  "ATAVILLOS ALTO": 3,
  "ATAVILLOS BAJO": 3,
  "AUCALLAMA": 50,
  "CHANCAY": 176,
  "IHUARI": 9,
  "LAMPIAN": 3,
  "PACARAOS": 3,
  "SAN MIGUEL DE ACOS": 4,
  "VEINTISIETE DE NOVIEMBRE": 3,
  "SANTA CRUZ DE ANDAMARCA": 2,
  "SUMBILCA": 3,
  "MATUCANA": 15,
  "ANTIOQUIA": 6,
  "CALLAHUANCA": 3,
  "CARAMPOMA": 2,
  "SAN PEDRO DE CASTA": 4,
  "CUENCA": 3,
  "CHICLA": 6,
  "HUANZA": 3,
  "HUAROCHIRI": 5,
  "LAHUAYTAMBO": 3,
  "LANGA": 4,
  "MARIATANA": 5,
  "RICARDO PALMA": 21,
  "SAN ANDRES DE TUPICOCHA": 5,
  "SAN BARTOLOME": 4,
  "SAN DAMIAN": 5,
  "SANGALLAYA": 2,
  "SAN JUAN DE TANTARANCHE": 2,
  "SAN LORENZO DE QUINTI": 5,
  "SAN MATEO": 13,
  "SAN MATEO DE OTAO": 6,
  "SAN PEDRO DE HUANCAYRE": 1,
  "SANTA CRUZ DE COCACHACRA": 8,
  "SANTA EULALIA": 37,
  "SANTIAGO DE ANCHUCAYA": 2,
  "SANTIAGO DE TUNA": 2,
  "SANTO DOMINGO DE LOS OLLEROS": 20,
  "SURCO": 6,
  "HUACHUPAMPA": 3,
  "SAN PEDRO DE LARAOS": 2,
  "SAN JUAN DE IRIS": 2,
  "CAJATAMBO": 6,
  "COPA": 4,
  "GORGOR": 6,
  "HUANCAPON": 4,
  "MANAS": 4,
  "HUACHO": 189,
  "AMBAR": 8,
  "CALETA DE CARQUIN": 18,
  "CHECRAS": 3,
  "HUALMAY": 75,
  "HUAURA": 97,
  "LEONCIO PRADO": 8,
  "PACCHO": 6,
  "SANTA LEONOR": 4,
  "SANTA MARIA": 107,
  "SAYAN": 66,
  "VEGUETA": 74,
  "BARRANCA": 195,
  "PARAMONGA": 66,
  "PATIVILCA": 54,
  "SUPE": 71,
  "SUPE PUERTO": 35,
  "OYON": 24,
  "NAVAN": 3,
  "CAUJUL": 3,
  "ANDAJES": 2,
  "PACHANGARA": 12,
  "COCHAMARCA": 6,
  "INDEPENDENCIA": 595,
  "LA MOLINA": 574,
  "LA VICTORIA": 640,
  "JESUS MARIA": 427,
  "LIMA": 1015,
  "ATE": 1671,
  "EL AGUSTINO": 566,
  "ANCON": 164,
  "PUENTE PIEDRA": 891,
  "SANTA ROSA": 68,
  "COMAS": 1495,
  "RIMAC": 560,
  "LINCE": 290,
  "MAGDALENA DEL MAR": 256,
  "SAN ISIDRO": 282,
  "MIRAFLORES": 478,
  "SURQUILLO": 338,
  "SANTIAGO DE SURCO": 1179,
  "LURIN": 248,
  "PACHACAMAC": 319,
  "PUCUSANA": 44,
  "PUNTA HERMOSA": 33,
  "PUNTA NEGRA": 25,
  "SAN BARTOLO": 24,
  "SANTA MARIA DEL MAR": 6,
  "CIENEGUILLA": 105,
  "VILLA MARIA DEL TRIUNFO": 1242,
  "LOS OLIVOS": 977,
  "CHACLACAYO": 138,
  "LURIGANCHO": 550,
  "PUEBLO LIBRE": 344,
  "SAN BORJA": 422,
  "SAN JUAN DE LURIGANCHO": 2731,
  "SAN JUAN DE MIRAFLORES": 1115,
  "SAN MARTIN DE PORRES": 1780,
  "SAN MIGUEL": 507,
  "SANTA ANITA": 631,
  "VILLA EL SALVADOR": 1171,
  "BELLAVISTA": 239,
  "CARMEN DE LA LEGUA - REYNOSO": 144,
  "LA PERLA": 193,
  "CALLAO": 1329,
  "LA PUNTA": 22,
  "VENTANILLA": 858,
  "MI PERU": 115
};
